[package]
authors = ["Pierre-Étienne Meunier <pe@pijul.org>"]
description = "Utilities to parse .ssh/config files, including helpers to implement ProxyCommand in Thrussh."
documentation = "https://docs.rs/thrussh-config"
edition = "2018"
include = ["Cargo.toml", "src/lib.rs", "src/proxy.rs"]
license = "Apache-2.0"
name = "thrussh-config"
repository = "https://nest.pijul.com/pijul/thrussh"
version = "0.6.0"

[dependencies]
dirs-next = "2.0"
futures = "0.3"
log = "0.4"
thiserror = "1.0"
tokio = {version = "1.0", features = ["io-util", "net", "macros", "process"]}
whoami = "1.0"
