[package]
authors = ["Pierre-Étienne Meunier <pe@pijul.org>"]
description = "A vector which zeroes its memory on clears and reallocations."
documentation = "https://pijul.org/cryptovec/doc/cryptovec"
include = ["Cargo.toml", "src/lib.rs"]
license = "Apache-2.0"
name = "russh-cryptovec"
publish = false
repository = "https://pijul.org/cryptovec"
version = "0.6.1"

[dependencies]
libc = "0.2"
winapi = {version = "0.3", features = ["basetsd", "minwindef", "memoryapi"]}
